#!/bin/bash

echo "PID del script ejercicio.sh: $$"
echo ""
echo "COMANDOS PRINCIPALES"
echo "-----------------------------------"
echo "touch nombreFichero  (para crear un fichero)"
echo "mkdir nombreCarpeta  (para crear una carpeta)"
echo "cat nombreFichero (para ver el contenido de un fichero)"
echo "echo 'mi contenido' >> nombreFichero (para añadir una nueva línea con contenido a un fichero)"
echo "rm nombreFichero (para eliminar el fichero)"
echo "rm -r nombreCarpeta (para eliminar carpetas con todo lo que tenga dentro)"
echo "rm -rf nombreDirectorio (para borrar un directorio)"
echo "mv nombreCarpeta nombreFivhero o nombreCarpeta (para mover ficheros o carpetas a otra carpeta)"
echo "ls (para listar un directorio)"
echo "pwd (para saber en qué directorio estamos)"
echo "clear para limpiar la pantalla"
echo "man nombreComando (para ver el manual de un comando)"
echo "cd nombreDirectorio  (para cambiar de directorio)"
echo "cd (te lleva al home)"
echo "ls -l (para mostrar la lista de archivos de forma  detallada)"
echo "who (para mostrar los usuarios que tiene el dispositivo en este momento)"
echo "uptime (muestra las estadisticas del dispositivo)"
echo "df -h (te enseña lo que esta utilizando el disco en ese momento)"
echo "free -h (te enseña lo que esta utilizando la memoria)"
echo " "
echo "COMANDOS ADICIONALES"
echo "-----------------------------------"
echo "menu (si no sabe de comandos y quieres realizarlo de manera mas sencilla esta es su opcion pero sera limitado el uso de comandos)"
echo "dados (un juego de dados cuando estas aburrido)"
echo "salir (si pulsa a Ctrl + C puedes cerrar el terminal)"
echo "r (si desea reiniciar el terminal)"
echo "fecha (te muestra la fecha y la hora que es)"
echo ""
echo "LOS QUE VOY A PONER AHORA ES PARA SI SE LES OLVIDA COMO PONER EL COMANDO PONER ESTOS QUE SON MAS FACILES DE RECORDAR"
echo "-----------------------------------"
echo "listar archivos = ls -l (para mostrar la lista de archivos de forma detallada) "
echo "usuarios = who (para mostrar los usuarios que tiene el dispositivo en este momento)"
echo "uso disco = df -f (te enseña lo que esta utilizando el disco en ese momento)"
echo "estadisticas = uptime (muestra las estadisticas del dispositivo)"
echo "consume memoria = free -h (te enseña lo que esta utilizando la memoria)"
